# Generated by Django 4.2.13 on 2024-06-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('comentario', models.BooleanField()),
                ('reaccion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.planes')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.roles')),
            ],
        ),
        migrations.CreateModel(
            name='SorteoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParticipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.participante')),
                ('idSorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.sorteo')),
            ],
        ),
        migrations.AddField(
            model_name='sorteo',
            name='idOrganizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.usuario'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='idPublicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.publicacion'),
        ),
        migrations.CreateModel(
            name='PlanesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('idPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.planes')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('idSorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.sorteo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('detalles', models.TextField()),
                ('idSorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.sorteo')),
            ],
        ),
        migrations.CreateModel(
            name='Ganadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHistorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.historialsorteo')),
                ('idParticipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteo.participante')),
            ],
        ),
    ]
